DROP TABLE USERS;
CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY 
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        NAME VARCHAR(200) NOT NULL, 
        LOGIN VARCHAR (20) NOT NULL, 
        PASSWORDHASH BIGINT NOT NULL
);

INSERT INTO USERS VALUES
(DEFAULT, 'Administrador','admin', 123456);
INSERT INTO USERS VALUES
(DEFAULT, 'Cliente','cliente', 123456);

DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS (
    COD BIGINT PRIMARY KEY 
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        NAME VARCHAR(200) NOT NULL, 
        PRICE DOUBLE NOT NULL
);


DROP TABLE LIST;
CREATE TABLE LIST (
    ID BIGINT PRIMARY KEY 
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        NAME VARCHAR(200) NOT NULL, 
        PRICE DOUBLE NOT NULL,
        QTDE BIGINT NOT NULL,
        TOTALPRICE DOUBLE
);

